config/routes.rb
Rails.application.routes.draw do


  resources :items do
    get :delete, on: :collection
    get :get_sample, on: :collection
    resources :joints, shallow: true, only: [:create, :destroy]
  end

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :destroy]

  resources :outfits, only: [:new, :create, :index, :destroy] do
    get :start, on: :collection
  end

  get('/', { to: 'outfits#start', as: 'first' })
  

end

app/models/outfit.rb
class Outfit < ApplicationRecord
  belongs_to :weather
  belongs_to :user


  has_many :joints, dependent: :destroy
  has_many :items, through: :joints
end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
  require 'httparty'
  require 'date'
  require 'time'

  def create
      w = Weather.where("created_at > ?", Date.today).last
      outfit = Outfit.new
      outfit.date = Date.today
      outfit.weather = w
      outfit.high_temp = w.high_temp
      outfit.user = current_user
      outfit.item_ids = outfit_params[:item_ids]
      ids = outfit.items
      if outfit.save
          flash[:success] = "An outfit is created!"
           redirect_to items_path
      else
          flash[:danger] = "Outfit is not created!"
           redirect_to items_path
      end
  end

  def start
      @weather = Weather.where("created_at >= ?", Time.now - 1.hour).last
      if @weather.blank?
          forecast = fetch_weather["DailyForecasts"]
          @weather = Weather.new(
              high_temp: forecast[0]["Temperature"]["Maximum"]["Value"],
              low_temp: forecast[0]["Temperature"]["Minimum"]["Value"],
              description: forecast[0]["Day"]["IconPhrase"],
              name: forecast[0]["Day"]["IconPhrase"],
              icon: forecast[0]["Day"]["Icon"]
          )
          @weather.icon_src = weatherImage(@weather.icon)
          if !@weather.save
              @weather = false     
          end       
      end
      getOutfit()
      checkItem()
  end

  def index
      @outfits = Outfit.where("user_id = ?", current_user).order("created_at desc").limit(10) 
  end

  def destroy
      outfit = Outfit.find params[:id]
      joints = Joint.where("outfit_id = :current_outfit", {current_outfit: outfit})
      joints.each do |j|
          j.destroy
      end
      outfit.destroy
      redirect_to outfits_path
  end

  private

  def fetch_weather
      city = 'Vancouver'
      country = 'ca'
      url = "http://dataservice.accuweather.com/forecasts/v1/daily/1day/53286?apikey=#{ENV["WEATHER_API_KEY"]}&metric=true"
      forecast = HTTParty.get(url,:headers =>{'Content-Type' => 'application/json'})
  end

  def getOutfit
      w = Weather.where("created_at > ?", Date.today).last
      @outfit = Outfit.where("user_id = :current AND high_temp >= :low AND high_temp <= :high", {current: current_user, high: w.high_temp + 4, low: w.high_temp - 4 }).last
  end

  def checkItem
      @item = Item.where("user_id = :current", {current: current_user }).last
  end

  def outfit_params
      params.require(:outfit).permit( :item_ids => [])
  end

  def weatherImage(icon)
      src=""
      case icon
      when 1, 2, 3
          src="sunny.png"
      when 4, 5, 6
          src="partly_cloudy.png"
      when 7, 8, 11
          src="cloud.png"
      when 12, 15, 18
          src="rain_light.png"
      when 13, 14, 16, 17
          src="rain_s_cloudy.png"
      when 19,20,21, 22, 23
          src="snowy.icon.png"
      else
          src="nothing"
      end
  end
end

app/views/outfits/_form.html.erb
<%= form_with(model: outfit, local: true) do |form| %>
  <% if outfit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(outfit.errors.count, "error") %> prohibited this outfit from being saved:</h2>

      <ul>
      <% outfit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :weather_id %>
    <%= form.text_field :weather_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :high_temp %>
    <%= form.number_field :high_temp %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/outfits/edit.html.erb
<h1>Editing Outfit</h1>

<%= render 'form', outfit: @outfit %>

<%= link_to 'Show', @outfit %> |
<%= link_to 'Back', outfits_path %>

app/views/outfits/index.html.erb
<main class="outfit-index">
<h2 class='title outfits-title'> My Outfits </h2>

<% if(@outfits) %>
    <ul class="ul-outfits">
        <% @outfits.each do |o| %>
            <li>
                <div class="outfit-date">
                    <%= o.date.to_formatted_s.to_date.strftime('%a, %d %b %Y') %>
                </div>
                <div class="outfit-weather"> 
                    <div class="outfit-weather-name">
                        <%=o.weather.description%>
                    </div>
                    <div>
                        <span>
                            <%= image_tag o.weather.icon_src, class: "outfit-weather-icon" %>
                        </span>
                        <span class="outfit-high-temp">
                            <%= o.weather.high_temp %> ºC 
                        </span>
                    </div>
                </div>
                <div class="each-outfit">
                    <% o.items.each do |i| %>
                        <div class="each-outfit-item">
                            <%= image_tag i.image.variant(resize: "100x100") %>
                        </div>
                    <%end%>
                </div>
                <%= link_to outfit_path(o.id), method: :delete, data: {confirm: "Are you sure?"}  do %>
                    <!--<div id="delete-icon" style="font-size: 1.5rem; color: lightgreen; display " > -->
                    <div id="delete-icon" class="trash" >
                         <i class="fas fa-trash-alt"></i> 
                    </div>
                <% end %>  
            </li> 
        <%end%>
    </ul>
<% end %>
</main>

app/views/outfits/new.html.erb
<h1>New Outfit</h1>

<%= render 'form', outfit: @outfit %>

<%= link_to 'Back', outfits_path %>

app/views/outfits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Weather:</strong>
  <%= @outfit.weather %>
</p>

<p>
  <strong>User:</strong>
  <%= @outfit.user %>
</p>

<p>
  <strong>High temp:</strong>
  <%= @outfit.high_temp %>
</p>

<p>
  <strong>Date:</strong>
  <%= @outfit.date %>
</p>

<%= link_to 'Edit', edit_outfit_path(@outfit) %> |
<%= link_to 'Back', outfits_path %>

app/views/outfits/start.html.erb
<main class="outfit-start">
    <% if (current_user) %>
        <div class="weather-info-box">
            <% if @weather %>

                <div class="weather-info">
                        <div>
                            <%= image_tag @weather.icon_src, class: "weather-icon" %>
                        </div>
                        <div>
                            <span class="high-temp">
                                <%= @weather.high_temp %> ºC 
                            </span>
                            <span class="slash">/</span>
                            <span class="low-temp">
                                <%= @weather.low_temp %> ºC
                            </span>
                        </div>
                        <div class="weather-name">
                                <%= @weather.name %>
                        </div>
                </div>
                <div class="date">
                    <%= @weather.created_at.to_formatted_s.to_date.strftime('%a, %d %b %Y') %>
                </div>

            <% else %>
                "No weather"
            <% end %>
        </div>
   
        <% if !(@item) %>
            <div class='first-info'>
                <h2 style="color: #4ba0b5;"> To plan your outfits, first add your fashion items.</h2> <br>
                <h5> First, store your items into your closet with 
                     <span>
                         <%= link_to new_item_path do %>
                           <button type="button" class="c-button ">Add Item</button>  
                        <% end %>
                     </span>. </h5>
                <h5> Then, to make outfits, click 
                     <span>
                         <%= link_to items_path do %>
                            <button type="button" class="c-button ">Closet</button>                
                         <% end %>
                     </span> to open your closet. </h5><br>
                <h5 style="text_align: center"> OR </h5>  <br>   
                <h5> 
                     <span> For trial, just get sample items with
                         <%= link_to get_sample_items_path do %>
                             <button type="button" class="c-button">Sample Items</button>
                         <% end %> 
                     </span>. Then, start to make outfits. 
                     
                </h5><br>

                <h2 style="color: #4ba0b5;"> Then, click logo to see proposal for this weather.</h2>
            </div>
        <% else %>
            <h2 class="proposal-title"> Proposal for today  </h2>
            <% if(@outfit) %>
                    <div class="suggestion">
                        <% @outfit.items.each do |i| %>
                            <div class="suggestion-item">
                                <%= image_tag i.image.variant(resize: "200x200") %>
                            </div>
                        <%end%>
                    </div> 
            <% else %>
                <div class='proposal-info'>
                    <p > Proposal is made from the outfits you have made before.  </p>
                    <p > There is no outfit history yet. </p>
                </div>
            <% end %>
        <% end %>
   
        <%= form_for :items,  url: items_path, method: :get do |f| %>
            <div class="select-season-occasion">
                <div>
                    <%= f.submit "Open Closet",  class: "btn btn-info closet-button" %>
                </div>
                <div class="option-names">
                    <div class="option-name"> Season </div>
                    <div class="option-name"> Occasion </div>                     
                </div>
                <div class="options">
                    <div class="radio-reform">
                        <%= collection_radio_buttons(:items, :season_id, Season.all, :id, :name, {}, {:class => 'radio-button'}) %>
                    </div>
                    <div class="radio-reform">
                        <%= collection_radio_buttons(:items, :occasion_id, Occasion.all, :id, :name, {}, {:class => 'radio-button'}) %>
                    </div>
                </div>

            </div>
        <% end %>
        
    <% else %>
            <h2 class="title start-title"> Design Your Outfit </h2>
            <div class="f-images">
                <%= image_tag("fashion8.jpg", :class => "f1")%>
                <%= image_tag("fashion9.jpg", :class => "f1")%>
                <%= image_tag("fashion23.jpg", :class => "f1")%>
                <%= image_tag("fashion12.jpg", :class => "f1")%>
            </div>

    <% end %>
   
</main>