config/routes.rb
Rails.application.routes.draw do


  resources :items do
    get :delete, on: :collection
    get :get_sample, on: :collection
    resources :joints, shallow: true, only: [:create, :destroy]
  end

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :destroy]

  resources :outfits, only: [:new, :create, :index, :destroy] do
    get :start, on: :collection
  end

  get('/', { to: 'outfits#start', as: 'first' })
  

end

app/models/joint.rb
class Joint < ApplicationRecord
  belongs_to :outfit
  belongs_to :item
end

app/controllers/joints_controller.rb
class JointsController < ApplicationController
  before_action :set_joint, only: [:show, :edit, :update, :destroy]

  # GET /joints
  # GET /joints.json
  def index
    @joints = Joint.all
  end

  # GET /joints/1
  # GET /joints/1.json
  def show
  end

  # GET /joints/new
  def new
    @joint = Joint.new
  end

  # GET /joints/1/edit
  def edit
  end

  # POST /joints
  # POST /joints.json
  def create
    @joint = Joint.new(joint_params)

    respond_to do |format|
      if @joint.save
        format.html { redirect_to @joint, notice: 'Joint was successfully created.' }
        format.json { render :show, status: :created, location: @joint }
      else
        format.html { render :new }
        format.json { render json: @joint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /joints/1
  # PATCH/PUT /joints/1.json
  def update
    respond_to do |format|
      if @joint.update(joint_params)
        format.html { redirect_to @joint, notice: 'Joint was successfully updated.' }
        format.json { render :show, status: :ok, location: @joint }
      else
        format.html { render :edit }
        format.json { render json: @joint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /joints/1
  # DELETE /joints/1.json
  def destroy
    @joint.destroy
    respond_to do |format|
      format.html { redirect_to joints_url, notice: 'Joint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_joint
      @joint = Joint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def joint_params
      params.require(:joint).permit(:outfit_id, :item_id)
    end
end

app/views/joints/_form.html.erb
<%= form_with(model: joint, local: true) do |form| %>
  <% if joint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(joint.errors.count, "error") %> prohibited this joint from being saved:</h2>

      <ul>
      <% joint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :outfit_id %>
    <%= form.text_field :outfit_id %>
  </div>

  <div class="field">
    <%= form.label :item_id %>
    <%= form.text_field :item_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/joints/edit.html.erb
<h1>Editing Joint</h1>

<%= render 'form', joint: @joint %>

<%= link_to 'Show', @joint %> |
<%= link_to 'Back', joints_path %>

app/views/joints/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Joints</h1>

<table>
  <thead>
    <tr>
      <th>Outfit</th>
      <th>Item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @joints.each do |joint| %>
      <tr>
        <td><%= joint.outfit %></td>
        <td><%= joint.item %></td>
        <td><%= link_to 'Show', joint %></td>
        <td><%= link_to 'Edit', edit_joint_path(joint) %></td>
        <td><%= link_to 'Destroy', joint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Joint', new_joint_path %>

app/views/joints/new.html.erb
<h1>New Joint</h1>

<%= render 'form', joint: @joint %>

<%= link_to 'Back', joints_path %>

app/views/joints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Outfit:</strong>
  <%= @joint.outfit %>
</p>

<p>
  <strong>Item:</strong>
  <%= @joint.item %>
</p>

<%= link_to 'Edit', edit_joint_path(@joint) %> |
<%= link_to 'Back', joints_path %>